workflows:
  android-debug:
    name: NovaPlay Ultra Debug

    environment:
      java: 17

    scripts:
      - name: Make Gradle executable
        script: |
          chmod +x gradlew

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk