workflows:
  nova-play-ultra-debug:
    name: NovaPlay Ultra - Debug
    environment:
      java: 17

    scripts:
      - name: Decode Debug Keystore
        script: |
          echo $DEBUG_KEYSTORE_BASE64 | base64 --decode > ${CM_BUILD_DIR}/debug.keystore

      - name: Make Gradle executable
        script: chmod +x gradlew

      - name: Clean
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk

  nova-play-ultra-release:
    name: NovaPlay Ultra - Release
    environment:
      vars:
        STORE_PASSWORD: $STORE_PASSWORD
        KEY_PASSWORD: $KEY_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
      java: 17
      groups:
        - keystore

    scripts:
      - name: Decode Release Keystore
        script: |
          echo $RELEASE_KEYSTORE_BASE64 | base64 --decode > ${CM_BUILD_DIR}/my-upload-key.jks

      - name: Make Gradle executable
        script: chmod +x gradlew

      - name: Clean
        script: ./gradlew clean

      - name: Build Release APK
        script: ./gradlew assembleRelease --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
